### PR TITLE
fix reconnect button, support for changing theme

### PR DESCRIPTION
**Pull request by sandsmark**

### CODE REVIEW

**Comment by vladest** [comment]
Martin,
selection is broke with this patch? what options we have?

**Comment by sandsmark** [comment]
what kind of selections?

**Comment by vladest** [comment]
Text selection. but in worse case we can just add popup to select whole message. that should be enough atm

**Comment by sandsmark** [comment]
ah, text selection, my bad, I'll fix

**Comment by sandsmark** [comment]
fixed it, and also fixed ctrl+c for copying (but this means that the input field loses focus), and when unselected the input field gets focus again

**Comment by vladest** [comment]
+1

**Pull request closed without merging**
